services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests  # Add tests volume mapping
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/event_planner
      - SECRET_KEY=your_secret_key_replace_with_actual_secret
      - OPENWEATHER_API_KEY=be285f8d3bf43db17bddb0009250b485
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_planner
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: