services:
  - type: web
    name: smart-event-planner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-event-planner-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOW_ORIGINS
        value: '["*"]'

databases:
  - name: smart-event-planner-db
    databaseName: smart_event_planner
    user: smart_event_planner_user
